// Regression tests for the classifier bugs listed under "Open" in CLAUDE.md.
//
// The two `real-2.1.226-*.jsonl` fixtures are redacted skeletons of actual
// sessions (`cctree fixture <session>`), committed because every one of
// these bugs was invisible to the synthetic fixtures — they only ever contained
// record shapes we already knew about. Unlike the synthetic ones these are NOT
// regenerated by `npm test`; they are captured evidence of one Claude Code
// version and should be added to, not replaced, after an upgrade.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseTranscript, parseText, stats } from '../src/parse.js';
import { buildGraph, annotate, collapse, looksForked } from '../src/graph.js';
import { assignLanes } from '../src/lanes.js';
import { renderAscii } from '../src/render-ascii.js';

const F = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');
// 47f354da carries a slash command's three plumbing records; aaf4e71a carries a
// typed prompt with an expansion embedded in it, and the richer attachment set.
const CMD = join(F, 'real-2.1.226-47f354da.jsonl');
const LIVE = join(F, 'real-2.1.226-aaf4e71a.jsonl');

const load = (file) => {
  const { records } = parseTranscript(file);
  return { records, graph: annotate(buildGraph(records)) };
};
const byKind = (graph, kind) => [...graph.nodes.values()].filter((n) => n.kind === kind);

test('uuid-less records are kept as sidecars and never enter the tree', () => {
  const { graph } = load(CMD);
  assert.equal(graph.sidecars.length, 9, 'every uuid-less record is retained');
  assert.deepEqual(
    [...new Set(graph.sidecars.map((r) => r.subkind))].sort(),
    ['ai-title', 'file-history-snapshot', 'last-prompt', 'mode', 'permission-mode'],
    'each sidecar keeps its own type as a subkind',
  );
  assert.equal(byKind(graph, 'sidecar').length, 0, 'and none of them became a node');
  for (const uuid of graph.nodes.keys()) {
    assert.ok(!String(uuid).startsWith('synthetic-'), `no synthetic id: ${uuid}`);
  }
  // The bug: 9 sidecars became 9 synthetic roots that were also 9 tips, and the
  // graph opened with a stack of orphan ◇ rows.
  assert.equal(graph.tips.length, 2, 'tips are real conversation ends, not sidecars');
});

test('nothing with a uuid falls through to unknown', () => {
  for (const file of [CMD, LIVE]) {
    const { records, graph } = load(file);
    assert.equal(byKind(graph, 'unknown').length, 0, `${file} has no unknown nodes`);
    // `unknown` surviving in stats is the drift signal we want left intact, so
    // assert on the histogram too rather than only on the tree.
    assert.equal(stats(records).kinds.unknown, undefined);
  }
});

test('attachments are in-chain nodes, not orphans, and carry their subkind', () => {
  const { graph } = load(LIVE);
  const attachments = byKind(graph, 'attachment');
  assert.equal(attachments.length, 11);
  for (const a of attachments) {
    assert.ok(a.subkind, 'every attachment names its flavour');
    assert.ok(a.parentUuid, 'attachments hang off the record they annotate');
    assert.ok(graph.nodes.has(a.parentUuid), 'and that parent is in the tree');
    assert.equal(a.promptNo, undefined, 'attachments are never numbered as prompts');
  }
  // Shape-based detection, so a subkind this code has never heard of still lands
  // as an attachment rather than as `unknown`.
  const subkinds = new Set(attachments.map((a) => a.subkind));
  for (const expected of ['skill_listing', 'plan_mode_exit', 'auto_mode', 'edited_text_file']) {
    assert.ok(subkinds.has(expected), `saw ${expected}`);
  }
});

test('slash-command plumbing is not counted or numbered as a user prompt', () => {
  const { graph } = load(CMD);
  const prompts = byKind(graph, 'prompt');
  assert.equal(prompts.length, 1, 'one typed prompt, not four');
  assert.equal(prompts[0].promptNo, 1);

  const commands = byKind(graph, 'command');
  assert.equal(commands.length, 3, 'caveat + invocation + stdout');
  for (const c of commands) assert.equal(c.promptNo, undefined, 'plumbing gets no #N');
  // The prompt numbering is the rewind recipe, so it must count only real turns.
  assert.deepEqual(
    [...graph.nodes.values()].filter((n) => n.promptNo != null).map((n) => n.promptNo),
    [1],
  );
});

test('a typed prompt that embeds an expansion is still a prompt', () => {
  // The trap. This session's opening prompt contains <command-name>,
  // <local-command-stdout> AND <local-command-caveat>, so detecting plumbing by
  // tag presence — the obvious reading of the bug report — silently discards the
  // one record the whole graph hangs off.
  const { records, graph } = load(LIVE);
  const opening = records.find((r) => r.uuid === graph.roots[0]);
  const rawText = String(opening.raw.message.content);
  assert.ok(rawText.includes('<command-name>'), 'fixture really does embed an expansion');
  assert.ok(rawText.includes('<local-command-caveat>'), 'and a caveat');

  assert.equal(opening.kind, 'prompt', 'residual text survives stripping, so it is a prompt');
  assert.equal(graph.nodes.get(opening.uuid).promptNo, 1);
  assert.ok(!opening.preview.includes('command-name'), 'preview shows what the human wrote');
  assert.ok(!opening.preview.includes('caveat'), 'not the caveat boilerplate in front of it');
  assert.equal(byKind(graph, 'prompt').length, 1);
});

test('plumbing detection keys on surviving text, not on tag presence', () => {
  const at = (i) => `2026-08-08T09:0${i}:00.000Z`;
  const user = (uuid, content, extra = {}) =>
    JSON.stringify({
      uuid, parentUuid: null, type: 'user', timestamp: at(1),
      message: { role: 'user', content }, ...extra,
    });

  const { records } = parseText(
    [
      user('p1', '<command-name>/foo</command-name>\n<command-args></command-args>'),
      user('p2', '<local-command-stdout>lots of output</local-command-stdout>'),
      user('p3', '<command-name>/foo</command-name>\nnow do the actual work'),
      // Half-flushed tag: a live session can be read mid-write, and an
      // unterminated tag must still strip to nothing rather than read as text.
      user('p4', '<local-command-stdout>output that never clos'),
      // Human-origin override: a paste-only prompt with no surviving text.
      user('p5', '<local-command-stdout>x</local-command-stdout>', { promptSource: 'typed' }),
      user('p6', '<local-command-caveat>c</local-command-caveat>', { origin: { kind: 'human' } }),
    ].join('\n'),
  );
  const kind = (u) => records.find((r) => r.uuid === u).kind;

  assert.equal(kind('p1'), 'command', 'tags only');
  assert.equal(kind('p2'), 'command', 'captured stdout only');
  assert.equal(kind('p3'), 'prompt', 'text survives stripping');
  assert.equal(kind('p4'), 'command', 'unterminated tag still strips');
  assert.equal(kind('p5'), 'prompt', 'promptSource overrides');
  assert.equal(kind('p6'), 'prompt', 'origin.kind=human overrides');
  assert.equal(records.find((r) => r.uuid === 'p3').preview, 'now do the actual work');
});

test('classification is role-first, so a renamed type keeps its meaning', () => {
  const { records, issues } = parseText(
    [
      // `type` values this build has never seen. Role still decides.
      JSON.stringify({
        uuid: 'n1', parentUuid: null, type: 'assistant-v2-from-the-future',
        timestamp: '2026-08-08T09:00:00.000Z',
        message: { role: 'assistant', content: [{ type: 'tool_use', name: 'Bash', id: 't1' }] },
      }),
      JSON.stringify({
        uuid: 'n2', parentUuid: 'n1', type: 'human-turn',
        timestamp: '2026-08-08T09:01:00.000Z',
        message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1' }] },
      }),
      // No uuid and a type nobody has heard of: absorbed as a sidecar rather
      // than rendering as an orphan root.
      JSON.stringify({ type: 'brand-new-sidecar-kind', sessionId: 's1', someState: 'x' }),
      // An attachment flavour from a later release.
      JSON.stringify({
        uuid: 'n3', parentUuid: 'n2', type: 'attachment',
        timestamp: '2026-08-08T09:02:00.000Z',
        attachment: { type: 'something_invented_later' },
      }),
    ].join('\n'),
  );
  assert.equal(issues.length, 0, 'the parser rejected nothing');
  assert.deepEqual(records.map((r) => r.kind), ['tool_use', 'tool_result', 'sidecar', 'attachment']);
  assert.equal(records[2].subkind, 'brand-new-sidecar-kind');
  assert.equal(records[3].subkind, 'something_invented_later');
});

test('a real session renders with no orphan or unknown rows', () => {
  const { graph } = load(CMD);
  collapse(annotate(graph));
  const out = renderAscii(annotate(graph), assignLanes(graph), { color: false });
  assert.ok(!out.includes('?'), 'the ? glyph is gone');
  assert.ok(!out.includes('unknown'), 'and so is the unknown label');
  // Three attachments and three plumbing records fold into runs instead of
  // pushing the conversation off the screen.
  assert.ok(out.split('\n').length < 12, `graph stays compact:\n${out}`);
});

test('looksForked stays quiet on real sessions, single or merged', () => {
  // Was a false positive twice over: sidecar records became disconnected roots,
  // and the check counted sessions instead of testing pairs, so any project with
  // two unrelated sessions tripped it in --all mode.
  for (const file of [CMD, LIVE]) {
    assert.deepEqual(looksForked(load(file).graph), [], `${file} alone reports no drift`);
  }
  const merged = annotate(buildGraph([CMD, LIVE].flatMap((f) => parseTranscript(f).records)));
  assert.equal(merged.roots.length, 3, 'a root per session, plus the /command caveat root');
  assert.deepEqual(looksForked(merged), [], 'unrelated sessions are not suspected forks');
});

test('looksForked still fires on the drift it exists to catch', () => {
  // A /branch copy whose uuids were rewritten: same cwd, the copied prefix keeps
  // the original timestamps so the ranges overlap, and nothing dedupes.
  const rec = (uuid, parentUuid, session, minute) =>
    JSON.stringify({
      uuid, parentUuid, sessionId: session, type: 'user', cwd: '/home/dev/work/demo',
      timestamp: `2026-08-08T09:${String(minute).padStart(2, '0')}:00.000Z`,
      message: { role: 'user', content: `turn ${uuid}` },
    });
  const drifted = annotate(
    buildGraph(
      parseText(
        [
          rec('orig-1', null, 'session-a', 0),
          rec('orig-2', 'orig-1', 'session-a', 1),
          // same conversation, copied, uuids rewritten -> no overlap to dedupe on
          rec('copy-1', null, 'session-b', 0),
          rec('copy-2', 'copy-1', 'session-b', 1),
        ].join('\n'),
      ).records,
    ),
  );
  assert.deepEqual(looksForked(drifted).sort(), ['session-a', 'session-b']);

  // Sequential sessions in the same directory are the common case, not drift.
  const sequential = annotate(
    buildGraph(
      parseText([rec('a-1', null, 'session-a', 0), rec('b-1', null, 'session-b', 30)].join('\n')).records,
    ),
  );
  assert.deepEqual(looksForked(sequential), [], 'disjoint time ranges are not a fork');
});
